// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBimpLRb40GMZZAB7UWdShSPx8Yzh2NBY0',
    appId: '1:1065067790074:web:7553ceaef836c149389343',
    messagingSenderId: '1065067790074',
    projectId: 'pokedex-flutter-a223b',
    authDomain: 'pokedex-flutter-a223b.firebaseapp.com',
    storageBucket: 'pokedex-flutter-a223b.firebasestorage.app',
    measurementId: 'G-Y9NJ8XDK28',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBimpLRb40GMZZAB7UWdShSPx8Yzh2NBY0',
    appId: '1:1065067790074:web:7553ceaef836c149389343',
    messagingSenderId: '1065067790074',
    projectId: 'pokedex-flutter-a223b',
    authDomain: 'pokedex-flutter-a223b.firebaseapp.com',
    storageBucket: 'pokedex-flutter-a223b.firebasestorage.app',
    measurementId: 'G-Y9NJ8XDK28',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDkmLpSltG-_cLDCHb_XFnb1Tfo15FftTM',
    appId: '1:1065067790074:ios:fed95aa807c82fc0389343',
    messagingSenderId: '1065067790074',
    projectId: 'pokedex-flutter-a223b',
    storageBucket: 'pokedex-flutter-a223b.firebasestorage.app',
    iosBundleId: 'com.example.pokedexApp',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDkmLpSltG-_cLDCHb_XFnb1Tfo15FftTM',
    appId: '1:1065067790074:ios:fed95aa807c82fc0389343',
    messagingSenderId: '1065067790074',
    projectId: 'pokedex-flutter-a223b',
    storageBucket: 'pokedex-flutter-a223b.firebasestorage.app',
    iosBundleId: 'com.example.pokedexApp',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCVfb40Afa3wuOpxIU_C3-CEM7WMmHn7Yw',
    appId: '1:1065067790074:android:5b9ebc2cbf07539c389343',
    messagingSenderId: '1065067790074',
    projectId: 'pokedex-flutter-a223b',
    storageBucket: 'pokedex-flutter-a223b.firebasestorage.app',
  );

}